import React from "react";
import { ArrowLeft, BookOpen, ShieldCheck } from "lucide-react";

export function TermsPage({ setView }) {
  return (
    <div className="max-w-3xl mx-auto w-full glass-panel p-8 rounded-xl border border-gray-800 flex flex-col gap-6">
      <button onClick={() => setView("home")} className="text-sm text-amber-500 hover:text-amber-400 flex items-center gap-1.5 w-fit">
        <ArrowLeft size={16} /> Back to Home
      </button>

      <div className="flex items-center gap-3 border-b border-gray-800 pb-4">
        <BookOpen className="text-amber-500" size={24} />
        <h1 className="text-2xl font-bold text-white">Terms and Conditions</h1>
      </div>

      <div className="text-sm text-gray-400 flex flex-col gap-4 leading-relaxed overflow-y-auto max-h-[500px] pr-2">
        <p className="font-semibold text-white">1. Agreement to Terms</p>
        <p>By using the RailExp ticketing application, you agree to comply with and be bound by the general rules and terms defined herein. If you disagree, you must immediately terminate access.</p>

        <p className="font-semibold text-white">2. Ticket Booking and Seat Allocation</p>
        <p>Seats are booked in real-time under General and Tatkal quotas. Allocation is subject to availability. Seat coordinates generated by the portal represent final reservation bindings.</p>

        <p className="font-semibold text-white">3. Cancellation and Refund Policy</p>
        <p>Cancellation is permitted for General quota reservations only. Cancellation of Tatkal reservations is strictly prohibited under railway service rules. Refunds for qualified cancellations are credited to the user's registered account.</p>

        <p className="font-semibold text-white">4. Catering Preferences</p>
        <p>E-catering (Veg/Non-Veg) selections are computed dynamically based on the specific train route's scheduling. Additional charges will apply based on the travel segments.</p>

        <p className="font-semibold text-white">5. Limitation of Liability</p>
        <p>RailExp is not responsible for delayed running schedules, route diversions, or system downtime caused by underlying database sync latencies.</p>
      </div>
    </div>
  );
}

export function PrivacyPage({ setView }) {
  return (
    <div className="max-w-3xl mx-auto w-full glass-panel p-8 rounded-xl border border-gray-800 flex flex-col gap-6">
      <button onClick={() => setView("home")} className="text-sm text-amber-500 hover:text-amber-400 flex items-center gap-1.5 w-fit">
        <ArrowLeft size={16} /> Back to Home
      </button>

      <div className="flex items-center gap-3 border-b border-gray-800 pb-4">
        <ShieldCheck className="text-fuchsia-500" size={24} />
        <h1 className="text-2xl font-bold text-white">Privacy Policy</h1>
      </div>

      <div className="text-sm text-gray-400 flex flex-col gap-4 leading-relaxed overflow-y-auto max-h-[500px] pr-2">
        <p className="font-semibold text-white">1. Information We Collect</p>
        <p>We collect registered user credentials, contact parameters (such as email and phone number), address structures, passenger names, ages, and genders to complete seat reservation allocations.</p>

        <p className="font-semibold text-white">2. How We Use Information</p>
        <p>Collected data is used strictly for authentication validation, reservation ticket builds, live running tracking, and pushing booking confirmations via email.</p>

        <p className="font-semibold text-white">3. Third-Party Disclosures</p>
        <p>Your details are never sold or rented. Passenger identities are shared strictly with official railway checking systems to validate travel rights.</p>

        <p className="font-semibold text-white">4. Data Security</p>
        <p>We implement secure database access layers, password bcrypt encryptions, and token verification schemes to prevent unauthorized modifications to booking states.</p>
      </div>
    </div>
  );
}
